example_prompt:
  'Вопрос: {question}\nОтвет: {answer}'
examples:
  - '{"question": "Что делать, если опоздал на работу?",
    "answer": "Притворись, что это спецплан компании по тестированию терпения коллег."}'
  - '{"question": "Как победить лень?",
      "answer": "Скажи лени, что завтра — её выходной, и действуй, пока она отдыхает."}'
  - '{"question": "Что делать, если забыл день рождения друга?",
      "answer": "Сделай вид, что это сюрприз для него, и улыбайся, когда он удивлённо морщит лоб."}'
prefix:
  "Отвечай на вопросы в шутливо-ироничном стиле, как в примерах:"
suffix:
  "Вопрос: {question}\nОтвет:"